version: '3'

services:
  nginx-server:
    build:
      context: ..
      dockerfile: containers/nginx-server/Dockerfile
      args:
        - OPENSSL_BRANCH=${OPENSSL_BRANCH}
        - LIBOQS_BRANCH=${LIBOQS_BRANCH}
        - OQSPROV_BRANCH=${OQSPROV_BRANCH}
        - QKDKEMPROV_BRANCH=${QKDKEMPROV_BRANCH}
        - QKD_ETSI_API_BRANCH=${QKD_ETSI_API_BRANCH}
        - QKD_BACKEND=${QKD_BACKEND}
        - DEFAULT_GROUPS=${DEFAULT_GROUPS}
    ports:
      - "4433:4433"
    environment:
      - DEFAULT_GROUPS=${DEFAULT_GROUPS}
      - QKD_BACKEND=${QKD_BACKEND}
      - SSL_CERT_TYPE=${SSL_CERT_TYPE}
      - ACCOUNT_ID=${ACCOUNT_ID}
    volumes:
      - ../qkd_certs:/opt/qkd_certs
    
  h2load-bench:
    build:
      context: ..
      dockerfile: containers/h2load-bench/Dockerfile
      args:
        - OPENSSL_BRANCH=${OPENSSL_BRANCH}
        - LIBOQS_BRANCH=${LIBOQS_BRANCH}
        - OQSPROV_BRANCH=${OQSPROV_BRANCH}
        - QKDKEMPROV_BRANCH=${QKDKEMPROV_BRANCH}
        - QKD_ETSI_API_BRANCH=${QKD_ETSI_API_BRANCH}
        - QKD_BACKEND=${QKD_BACKEND}
    network_mode: "host"
    environment:
      - QKD_BACKEND=${QKD_BACKEND}
      - ACCOUNT_ID=${ACCOUNT_ID}
    volumes:
      - ../qkd_certs:/opt/qkd_certs
      - ../benchmarks/data:/benchmarks/data