worker_processes auto;
events {
    worker_connections 1024;
}
http {
    include mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;
    # HTTPS server
    server {
        listen 0.0.0.0:4433 ssl;
        server_name localhost;
        access_log logs/access.log;
        error_log logs/error.log;
        # Use dilithium3 as default certificate
        ssl_certificate /opt/certs/dilithium/dilithium3_entity_cert.pem;
        ssl_certificate_key /opt/certs/dilithium/dilithium3_entity_key.pem;
        ssl_session_cache shared:SSL:1m;
        ssl_session_timeout 5m;
        ssl_protocols TLSv1.3;
        # Configure supported KEMs from environment variable
        ssl_ecdh_curve $DEFAULT_GROUPS;
        location / {
            root html;
            index index.html index.htm;
        }
    }
}